### ISSUE TITLE
Failed to boot app if unsupported template files present

### ISSUE THREAD

**Issue by igneus** [hanami/view#107] opened 2016-07-31 12:46 UTC
Some text editors have a habit of creating automatic backups of edited files. Emacs is among them.
The backup files (with tilde added at the end of the file name) in a view directory make hanami crash:

```
Boot Error

Something went wrong while loading /home/igneus/src/ruby/db.inadiutorium/config.ru
RuntimeError: No template engine registered for index.html.erb~

/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:160:in `module_eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/tilt-2.0.5/lib/tilt.rb:43:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/template.rb:12:in `initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/templates_finder.rb:73:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/templates_finder.rb:73:in `block in find'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/templates_finder.rb:72:in `map'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/templates_finder.rb:72:in `find'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/layout_registry.rb:54:in `templates'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/registry.rb:123:in `template_for'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/registry.rb:104:in `block in prepare_views!'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/registry.rb:103:in `prepare_views!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/registry.rb:98:in `prepare!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering/layout_registry.rb:24:in `initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering.rb:281:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering.rb:281:in `registry'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering.rb:286:in `load_registry!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/rendering.rb:269:in `load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/configuration.rb:421:in `block in load!'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view/configuration.rb:421:in `load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-view-0.7.0/lib/hanami/view.rb:261:in `load!'
(eval):3:in `_load_view_framework!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:160:in `module_eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:160:in `_load_view_framework!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:154:in `load_frameworks!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:33:in `block in load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:28:in `synchronize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/loader.rb:28:in `load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/application.rb:195:in `load!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/application.rb:75:in `initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:9:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:9:in `mount'
/home/igneus/src/ruby/db.inadiutorium/config/environment.rb:8:in `block in <top (required)>'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-router-0.7.0/lib/hanami/router.rb:268:in `instance_eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-router-0.7.0/lib/hanami/router.rb:268:in `define'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-router-0.7.0/lib/hanami/router.rb:230:in `initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:49:in `new'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:49:in `prepare_middleware_stack!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:32:in `block in initialize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:30:in `synchronize'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/hanami-0.7.3/lib/hanami/container.rb:30:in `initialize'
/home/igneus/src/ruby/db.inadiutorium/config.ru:3:in `new'
/home/igneus/src/ruby/db.inadiutorium/config.ru:3:in `block in inner_app'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
/home/igneus/src/ruby/db.inadiutorium/config.ru:1:in `new'
/home/igneus/src/ruby/db.inadiutorium/config.ru:1:in `inner_app'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:113:in `eval'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:113:in `inner_app'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:103:in `assemble_app'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/shotgun-0.9.1/lib/shotgun/static.rb:14:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/home/igneus/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/igneus/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

I would find it more convenient to ignore unknown files rather than crash on them.

**Comment by cllns** [comment] 2016-07-31 22:03
Thanks for this issue! Many of us use `vim` so we never know about these kinds of errors with other text editors.

This is definitely something we want to fix! 

Could you try to write a failing test that demonstrates this issue?

**Comment by joneslee85** [comment] 2016-08-01 04:25
We should probably gracefully ignore unsupported template files on first scan and only raise error when user access the page that render templates. Sound like a good enhancement PR. Anyone up for it? I could provide guidance if needed.

**Comment by akhramov** [comment] 2016-08-07 14:49
@joneslee85 may I take this? 
My idea is to make Tilt's template initialization lazy. So error will be raised either on [Hanami::View::Template#render](https://github.com/hanami/view/blob/fd219cf651e0fff9833027c8fb3c9d5bc199d8ca/lib/hanami/view/template.rb#L40-L42) or [Hanami::View::Template#format] (https://github.com/hanami/view/blob/fd219cf651e0fff9833027c8fb3c9d5bc199d8ca/lib/hanami/view/template.rb#L26-L28).

**Comment by fleadope** [comment] 2016-08-26 16:07
I can confirm this - I was getting the same error with my bundle installed to 'vendor/bundle' - many of the gems have template files with a "*.tt" extension, and tilt barfs when it comes across them in the find method. 

When I moved my bundled files to '.bundle,' the error resolved.

**Comment by igneus** [comment] 2016-08-26 16:26
@fleadope that's quite scary. I would not expect the framework to look for templates in any other directory than the views directory.

**Comment by AlfonsoUceda** [comment] 2017-01-21 15:31
@jodosha what would we do whit this issue?

**Comment by igneus** [comment] 2017-01-21 18:53
@AlfonsoUceda As the person probably most annoyed by this issue, I have been planning to implement the "ignore unsupported template files" solution and submit a PR sometime in the near future.

**Comment by AlfonsoUceda** [comment] 2017-01-21 19:13
thanks @igneus ;)

**Comment by mereghost** [comment] 2017-02-06 17:02
@igneus just to set you on track the issue is caused by the [`TemplatesFinder#L96`](https://github.com/hanami/view/blob/master/lib/hanami/view/rendering/templates_finder.rb#L96) as it searches for the `action_name.*.*`. =)

**Comment by igneus** [comment] 2017-02-06 17:07
@mereghost If you want to take over this issue, go for it. I won't get to it neither today, nor tomorrow.

**Comment by jodosha** [comment] 2017-02-23 13:20
Closing this as it would require a major change in the loading process. The quick, non standard solution is avoid the editors to create backup files and to ignore them in `.gitignore`.

**Closed by jodosha** 2017-02-23 13:20 UTC
Labels: bug, waiting
